version: "3"
services:
  web-echo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ZING_MP3_VERSION=${ZING_MP3_VERSION}
      - ZING_MP3_SECRET=${ZING_MP3_SECRET}
      - ZING_MP3_API_KEY=${ZING_MP3_API_KEY}
        # domain and https
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    external: true
    name: ${NETWORK_NAME}

