name: Publish docs

on:
  push:
    branches: [main]
    paths: [README.md, docs/**]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        env:
          DOCS_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          curl -s -X POST -H "Authorization: $DOCS_TOKEN" https://react-photo-album.com/api/publish
